name: Deploy to Server

on:
  push:
    branches:
      - main  # Hangi branch'e kod atınca çalışsın?

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek ve Sunucuya Baglan
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # 1. Proje klasörüne git
            cd /root/katalog-app
            
            # 2. En güncel kodları GitHub'dan çek
            git pull origin main
            
            # 3. Docker ile sistemi güncelle ve yeniden başlat
            docker-compose up -d --build
            
            # 4. Gereksiz dolan hafızayı temizle (isteğe bağlı)
            docker image prune -f