name: Deploy to Server

on:
  push:
    branches:
      - main  # Hangi branch'e kod atınca çalışsın?

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek ve Sunucuya Baglan
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # 1. Proje klasörüne git
            cd /opt/www/fogcatalog/katalog-saas-frontend/
            
            # 2. Kodu Güncelle
            git fetch --all
            git reset --hard origin/main
            
            # 3. SİHİRLİ DOKUNUŞ: 'down' yok, sadece 'up --build' var!
            # Bu komut şu sırayla çalışır:
            # a) Site çalışmaya devam ederken arkada sessizce yeni 'build' alır.
            # b) Build bittiği an, eski container'ı durdurup milisaniyeler içinde yenisini koyar.
            docker-compose up -d --build --remove-orphans
            
            # 4. Temizlik (Eski image'ları siler)
            docker image prune -f