name: Deploy to Server

on:
  push:
    branches:
      - main  # Buradaki '#' işaretlerini kaldırdık, artık otomatik.
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek ve Sunucuya Baglan
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} 
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22  
          script: |
            # 1. Klasöre git
            cd /opt/www/fogcatalog/katalog-saas-frontend/ || { echo "Klasör bulunamadı!"; exit 1; }
            
            # 2. Kodu Güncelle
            git fetch --all
            git reset --hard origin/main
            
            # 3. Docker Build ve Restart
            docker compose up -d --build --remove-orphans || /usr/local/bin/docker-compose up -d --build --remove-orphans
            
            # 4. Temizlik
            docker image prune -f